/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedManagementRouteImport } from './routes/_authed/management'
import { Route as AuthedManagementUsersRouteImport } from './routes/_authed/management/users'
import { Route as AuthedManagementConfigurationsRouteImport } from './routes/_authed/management/configurations'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedManagementRoute = AuthedManagementRouteImport.update({
  id: '/management',
  path: '/management',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedManagementUsersRoute = AuthedManagementUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedManagementRoute,
} as any)
const AuthedManagementConfigurationsRoute =
  AuthedManagementConfigurationsRouteImport.update({
    id: '/configurations',
    path: '/configurations',
    getParentRoute: () => AuthedManagementRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/management': typeof AuthedManagementRouteWithChildren
  '/management/configurations': typeof AuthedManagementConfigurationsRoute
  '/management/users': typeof AuthedManagementUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/management': typeof AuthedManagementRouteWithChildren
  '/management/configurations': typeof AuthedManagementConfigurationsRoute
  '/management/users': typeof AuthedManagementUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/management': typeof AuthedManagementRouteWithChildren
  '/_authed/management/configurations': typeof AuthedManagementConfigurationsRoute
  '/_authed/management/users': typeof AuthedManagementUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/management'
    | '/management/configurations'
    | '/management/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/management'
    | '/management/configurations'
    | '/management/users'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/management'
    | '/_authed/management/configurations'
    | '/_authed/management/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/management': {
      id: '/_authed/management'
      path: '/management'
      fullPath: '/management'
      preLoaderRoute: typeof AuthedManagementRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/management/users': {
      id: '/_authed/management/users'
      path: '/users'
      fullPath: '/management/users'
      preLoaderRoute: typeof AuthedManagementUsersRouteImport
      parentRoute: typeof AuthedManagementRoute
    }
    '/_authed/management/configurations': {
      id: '/_authed/management/configurations'
      path: '/configurations'
      fullPath: '/management/configurations'
      preLoaderRoute: typeof AuthedManagementConfigurationsRouteImport
      parentRoute: typeof AuthedManagementRoute
    }
  }
}

interface AuthedManagementRouteChildren {
  AuthedManagementConfigurationsRoute: typeof AuthedManagementConfigurationsRoute
  AuthedManagementUsersRoute: typeof AuthedManagementUsersRoute
}

const AuthedManagementRouteChildren: AuthedManagementRouteChildren = {
  AuthedManagementConfigurationsRoute: AuthedManagementConfigurationsRoute,
  AuthedManagementUsersRoute: AuthedManagementUsersRoute,
}

const AuthedManagementRouteWithChildren =
  AuthedManagementRoute._addFileChildren(AuthedManagementRouteChildren)

interface AuthedRouteChildren {
  AuthedManagementRoute: typeof AuthedManagementRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedManagementRoute: AuthedManagementRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
